GAMEMODES = {
	[1] = {0, "FFA", "Kill others with randomly generated loadouts.", true},
	[2] = {1, "Cranked", "FFA with kills granting the player increased movement capabilities.", false},
	[3] = {2, "Gun Game", "FFA with players progressing throguh a ladder of numerous weapons.", false},
	[4] = {3, "Shotty Snipers", "FFA with loadouts always consisting of a sniper and a shotgun.", true},
	[5] = {4, "Fiesta", "FFA with every player sharing the same loadout, with a new loadout being generated periodically.", true},
	[6] = {5, "Quickdraw", "FFA with secondaries only.", true},
	[7] = {6, "KOTH", "FFA with a specific part of the map giving score if inside of said area.", false},
	[8] = {7, "VIP", "FFA with players fighting over VIP status, said status giving them score.", false},
	[9] = {8, "Overkill", "FFA with no weapon restrictions.", true},
	[10] = {9, "Fisticuffs", "FFA with only melee weapons.", false}
}

MAPS = {
	[1] = {"tm_arctic", "Arctic", "maps/thumb/tm_arctic.png", true, 0},
	[2] = {"tm_bridge", "Bridge", "maps/thumb/tm_bridge.png", true, 0},
	[3] = {"tm_corrugated", "Corrugated", "maps/thumb/tm_corrugated.png", true, 0},
	[4] = {"tm_disequilibrium", "Disequilibrium", "maps/thumb/tm_disequilibrium.png", true, 0},
	[5] = {"tm_grid", "Grid", "maps/thumb/tm_grid.png", true, 0},
	[6] = {"tm_initial", "Initial", "maps/thumb/tm_initial.png", true, 5},
	[7] = {"tm_legacy", "Legacy", "maps/thumb/tm_legacy.png", true, 5},
	[8] = {"tm_liminal_pool", "Liminal Pool", "maps/thumb/tm_liminal_pool.png", true, 0},
	[9] = {"tm_mall", "Mall", "maps/thumb/tm_mall.png", true, 0},
	[10] = {"tm_mephitic", "Mephitic", "maps/thumb/tm_mephitic.png", true, 0},
	[11] = {"tm_nuketown", "Nuketown", "maps/thumb/tm_nuketown.png", true, 5},
	[12] = {"tm_oxide", "Oxide", "maps/thumb/tm_oxide.png", true, 0},
	[13] = {"tm_rig", "Rig", "maps/thumb/tm_rig.png", true, 0},
	[14] = {"tm_rust", "Rust", "maps/thumb/tm_rust.png", true, 5},
	[15] = {"tm_sanctuary", "Sanctuary", "maps/thumb/tm_sanctuary.png", true, 0},
	[16] = {"tm_shipment", "Shipment", "maps/thumb/tm_shipment.png", true, 5},
	[17] = {"tm_shoot_house", "Shoot House", "maps/thumb/tm_shoot_house.png", true, 5},
	[18] = {"tm_station", "Station", "maps/thumb/tm_station.png", true, 0},
	[19] = {"tm_villa", "Villa", "maps/thumb/tm_villa.png", true, 0},
	[20] = {"tm_wreck", "Wreck", "maps/thumb/tm_wreck.png", true, 0}
}

AVAILABLEMAPS = {}
for _, v in ipairs(MAPS) do
	if v[4] == true then table.insert(AVAILABLEMAPS, v[1]) end
end

KOTHPOS = {
	["tm_arctic"] = {Origin = Vector(504, 384, 320), BrushSize = Vector(120, 112, 64)},
	["tm_bridge"] = {Origin = Vector(-3552, 96, 484), BrushSize = Vector(224, 288, 64)},
	["tm_corrugated"] = {Origin = Vector(192, 516, 188), BrushSize = Vector(64, 252, 60)},
	["tm_disequilibrium"] = {Origin = Vector(-280, 1940, 1064), BrushSize = Vector(96, 100, 72)},
	["tm_grid"] = {Origin = Vector(0, -1408, -560), BrushSize = Vector(128, 256, 112)},
	["tm_initial"] = {Origin = Vector(-136, 0, 68), BrushSize = Vector(104, 128, 68)},
	["tm_legacy"] = {Origin = Vector(-352, -416, 512), BrushSize = Vector(148, 148, 64)},
	["tm_liminal_pool"] = {Origin = Vector(0, 1184, 144), BrushSize = Vector(128, 176, 80)},
	["tm_mall"] = {Origin = Vector(2180, 1536, 72), BrushSize = Vector(108, 216, 64)},
	["tm_mephitic"] = {Origin = Vector(960, -320, 2748), BrushSize = Vector(96, 96, 60)},
	["tm_nuketown"] = {Origin = Vector(-89, 238, 128), BrushSize = Vector(108, 120, 64)},
	["tm_oxide"] = {Origin = Vector(550, 1800, -176), BrushSize = Vector(192, 144, 64)},
	["tm_rig"] = {Origin = Vector(-1024, -1024, -584), BrushSize = Vector(256, 256, 128)},
	["tm_rust"] = {Origin = Vector(608, 1252, -196), BrushSize = Vector(164, 144, 128)},
	["tm_sanctuary"] = {Origin = Vector(-472, 888, 10), BrushSize = Vector(152, 168, 90)},
	["tm_shipment"] = {Origin = Vector(0, 0, 64), BrushSize = Vector(64, 64, 64)},
	["tm_shoot_house"] = {Origin = Vector(-168, -437, 192), BrushSize = Vector(168, 116.5, 63.5)},
	["tm_station"] = {Origin = Vector(-300, 496, 468), BrushSize = Vector(108, 264, 62)},
	["tm_villa"] = {Origin = Vector(128, -880, -64), BrushSize = Vector(128, 112, 64)},
	["tm_wreck"] = {Origin = Vector(244, -192, 8), BrushSize = Vector(140, 112, 80)}
}

WEAPONS = {}
WEAPONS[1] = {"tfa_ins2_aa12", "AA-12", "primary", "shotgun"}
WEAPONS[2] = {"tfa_ins2_acrc", "ACR", "primary", "rifle"}
WEAPONS[3] = {"tfa_ins2_aek971", "AEK-971", "primary", "rifle"}
WEAPONS[4] = {"tfa_ins2_ak12", "AK-12", "primary", "rifle"}
WEAPONS[5] = {"tfa_ins2_ak400", "AK-400", "primary", "rifle"}
WEAPONS[6] = {"tfa_ins2_akms", "AK-47", "primary", "rifle"}
WEAPONS[7] = {"tfa_ins2_aks_r", "AKS-74U", "primary", "smg"}
WEAPONS[8] = {"tfa_cold_war_american180", "American-180", "primary", "smg"}
WEAPONS[9] = {"tfa_ins2_abakan", "AN-94", "primary", "rifle"}
WEAPONS[10] = {"tfa_ins2_ar57", "AR-57", "primary", "smg"}
WEAPONS[11] = {"tfa_inss_asval", "AS-VAL", "primary", "rifle"}
WEAPONS[12] = {"tfa_pd2_ash12", "ASh-12", "primary", "rifle"}
WEAPONS[13] = {"tfa_fml_csgo_aug", "AUG A2", "primary", "rifle"}
WEAPONS[14] = {"tfa_ins2_wpn_avt40", "AVT-40", "primary", "rifle"}
WEAPONS[15] = {"tfa_cod_accuracy_international_l115a3", "AWM", "primary", "sniper"}
WEAPONS[16] = {"tfa_ins2_warface_ax308", "AX-308", "primary", "sniper"}
WEAPONS[17] = {"tfa_ins2_barrett_m98_bravo", "Barrett M98B", "primary", "sniper"}
WEAPONS[18] = {"tfa_ins2_mx4", "Beretta Mx4", "primary", "smg"}
WEAPONS[19] = {"rust_bow", "Bow", "secondary", "sniper"}
WEAPONS[20] = {"tfa_bo3_bowiezm", "Bowie Knife", "melee"}
WEAPONS[21] = {"tfa_ins2_br99", "BR99", "primary", "shotgun"}
WEAPONS[22] = {"tfa_doibren", "Bren", "primary", "lmg"}
WEAPONS[23] = {"tfa_bo3_butterfly", "Butterfly Knife", "melee"}
WEAPONS[24] = {"tfa_bo3_bowie", "Carver", "melee"}
WEAPONS[25] = {"tfa_ins2_m4_9mm", "Colt 9mm", "primary", "smg"}
WEAPONS[26] = {"tfa_coonan_357", "Coonan .357", "secondary", "pistol"}
WEAPONS[27] = {"rust_crossbow", "Crossbow", "primary", "sniper"}
WEAPONS[28] = {"tfa_ins2_cz75", "CZ 75", "secondary", "pistol"}
WEAPONS[29] = {"tfa_ins2_cz805", "CZ 805", "primary", "rifle"}
WEAPONS[30] = {"yurie_eft_semin_push_dagger", "Dagger", "melee"}
WEAPONS[31] = {"tfa_ins2_deagle", "Desert Eagle", "secondary", "pistol"}
WEAPONS[32] = {"tfa_ins2_warface_amp_dsr1", "DSR-50", "primary", "sniper"}
WEAPONS[33] = {"tfa_dualmac", "Dual Mac 10s", "primary", "pistol"}
WEAPONS[34] = {"tfa_l4d2_skorpion_dual", "Dual Skorpions", "primary", "pistol"}
WEAPONS[35] = {"tfa_ins2_famas", "FAMAS", "primary", "rifle"}
WEAPONS[36] = {"tfa_doifg42", "FG 42", "primary", "lmg"}
WEAPONS[37] = {"tfa_bo3_axe", "Fire Axe", "melee"}
WEAPONS[38] = {"tfa_bo3_fists", "Fists", "melee"}
WEAPONS[39] = {"tfa_ins2_fiveseven_eft", "Fiveseven", "secondary", "pistol"}
WEAPONS[40] = {"tfa_codww2_flamethrower", "Flamethrower", "primary", "special"}
WEAPONS[41] = {"tfa_ins2_fn_2000", "FN 2000", "primary", "rifle"}
WEAPONS[42] = {"tfa_ins2_fn_fal", "FN FAL", "primary", "rifle"}
WEAPONS[43] = {"tfa_ins2_fnp45", "FNP-45", "secondary", "pistol"}
WEAPONS[44] = {"tfa_ins2_g28", "G28", "primary", "rifle"}
WEAPONS[45] = {"tfa_ins2_g36a1", "G36A1", "primary", "rifle"}
WEAPONS[46] = {"tfa_ins2_wpn_g3a3", "G3A3", "primary", "rifle"}
WEAPONS[47] = {"tfa_ins2_wpn_imigalilarm", "Galil", "primary", "rifle"}
WEAPONS[48] = {"tfa_glk_gen4", "Glock 18", "secondary", "pistol"}
WEAPONS[49] = {"grenade", "Grenade", "none", "explosive"} -- we have a grenade entry for kill tracking
WEAPONS[50] = {"tfa_ins2_groza", "Groza", "primary", "rifle"}
WEAPONS[51] = {"tfa_ins2_gsh18", "GSH-18", "secondary", "pistol"}
WEAPONS[52] = {"tfa_ins2_hk416", "HK416", "primary", "rifle"}
WEAPONS[53] = {"tfa_ins2_fml_hk53", "HK53", "primary", "rifle"}
WEAPONS[54] = {"tfa_ins2_cq300", "Honey Badger", "primary", "rifle"}
WEAPONS[55] = {"tfa_howa_type_64", "Howa Type 64", "primary", "rifle"}
WEAPONS[56] = {"tfa_ins2_imbelia2", "Imbel IA2", "primary", "rifle"}
WEAPONS[57] = {"tfa_ins2_warface_cheytac_m200", "Intervention", "primary", "sniper"}
WEAPONS[58] = {"ryry_tfa_chainsaw", "KAC ChainSAW", "primary", "lmg"}
WEAPONS[59] = {"tfa_doi_kar98k", "Kar98k", "primary", "sniper"}
WEAPONS[60] = {"tfa_karambit", "Karambit", "melee"}
WEAPONS[61] = {"tfa_km2000_knife", "KM-2000", "melee"}
WEAPONS[62] = {"tfa_ins2_krissv", "KRISS Vector", "primary", "smg"}
WEAPONS[63] = {"tfa_coldwar_ks23", "KS-23", "primary", "shotgun"}
WEAPONS[64] = {"tfa_ins2_ksg", "KSG", "primary", "shotgun"}
WEAPONS[65] = {"yurie_eft_united_cutlery_m48_kukri", "Kukri", "melee"}
WEAPONS[66] = {"tfa_ins2_l85a2", "L85", "primary", "rifle"}
WEAPONS[67] = {"tfa_doi_enfield", "Lee Enfield", "primary", "sniper"}
WEAPONS[68] = {"tfa_doilewis", "Lewis Gun", "primary", "lmg"}
WEAPONS[69] = {"tfa_ins2_zm_lr300", "LR-300", "primary", "rifle"}
WEAPONS[70] = {"tfa_doi_garand", "M1 Garand", "primary", "rifle"}
WEAPONS[71] = {"tfa_usurper", "M134 Minigun", "primary", "lmg"}
WEAPONS[72] = {"tfa_ins2_m14retro", "M14", "primary", "rifle"}
WEAPONS[73] = {"tfa_nam_m1911", "M1911", "secondary", "pistol"}
WEAPONS[74] = {"tfa_doim1918", "M1918", "primary", "lmg"}
WEAPONS[75] = {"tfa_doim1919", "M1919", "primary", "lmg"}
WEAPONS[76] = {"tfa_ins2_minimi", "M249", "primary", "lmg"}
WEAPONS[77] = {"tfa_doim3greasegun", "M3 Grease Gun", "secondary", "smg"}
WEAPONS[78] = {"tfa_ins2_colt_m45", "M45A1", "secondary", "pistol"}
WEAPONS[79] = {"tfa_ins2_eftm4a1", "M4A1", "primary", "rifle"}
WEAPONS[80] = {"tfa_nam_m79", "M79", "primary", "explosive"}
WEAPONS[81] = {"tfa_ins2_m9", "M9", "secondary", "pistol"}
WEAPONS[82] = {"tfa_ilopn_m9_phrobis", "M9 Bayonet", "melee"}
WEAPONS[83] = {"bocw_mac10_alt", "Mac 10", "secondary", "smg"}
WEAPONS[84] = {"tfa_ararebo_bf1", "Mace", "melee"}
WEAPONS[85] = {"tfa_ins2_pm", "Makarov", "secondary", "pistol"}
WEAPONS[86] = {"tfa_tfre_maresleg", "Mare's Leg", "secondary", "pistol"}
WEAPONS[87] = {"tfa_fml_lefrench_mas38", "Mas 38", "primary", "smg"}
WEAPONS[88] = {"tfa_doimg34", "MG 34", "primary", "lmg"}
WEAPONS[89] = {"tfa_doimg42", "MG 42", "primary", "lmg"}
WEAPONS[90] = {"tfa_ins2_mk14ebr", "MK 14 EBR", "primary", "rifle"}
WEAPONS[91] = {"tfa_ins2_mk23", "MK 23", "secondary", "pistol"}
WEAPONS[92] = {"tfa_fml_inss_mk18", "MK18", "primary", "rifle"}
WEAPONS[93] = {"tfa_ins2_swmodel10", "Model 10", "secondary", "pistol"}
WEAPONS[94] = {"tfa_ins2_mosin_nagant", "Mosin Nagant", "primary", "sniper"}
WEAPONS[95] = {"tfa_doimp40", "MP 40", "primary", "smg"}
WEAPONS[96] = {"tfa_ins2_mp443", "MP-443", "secondary", "pistol"}
WEAPONS[97] = {"tfa_ww1_mp18", "MP18", "primary", "smg"}
WEAPONS[98] = {"tfa_inss2_hk_mp5a5", "MP5", "primary", "smg"}
WEAPONS[99] = {"tfa_ins2_mp5k", "MP5K", "secondary", "smg"}
WEAPONS[100] = {"tfa_ins2_mp7", "MP7", "primary", "smg"}
WEAPONS[101] = {"tfa_ins2_warface_bt_mp9", "MP9", "primary", "smg"}
WEAPONS[102] = {"tfa_jw_tti_mpx", "MPX", "primary", "smg"}
WEAPONS[103] = {"tfa_ins2_mr96", "MR-96", "secondary", "pistol"}
WEAPONS[104] = {"tfa_ins2_mc255", "MTs225", "primary", "shotgun"}
WEAPONS[105] = {"tfa_bocw_nailgun", "Nailgun", "secondary", "pistol"}
WEAPONS[106] = {"tfa_ins2_nova", "Nova", "primary", "shotgun"}
WEAPONS[107] = {"tfa_bo3_nunchucks", "Nunchucks", "melee"}
WEAPONS[108] = {"tfa_l4d2_osp18", "OSP-18", "secondary", "pistol"}
WEAPONS[109] = {"tfa_ins2_ots_33_pernach", "OTs-33 Pernach", "secondary", "pistol"}
WEAPONS[110] = {"tfa_doiowen", "Owen Gun", "primary", "smg"}
WEAPONS[111] = {"tfa_ins2_p320_m18", "P320", "secondary", "pistol"}
WEAPONS[112] = {"tfa_fml_p90_tac", "P90", "primary", "smg"}
WEAPONS[113] = {"tfa_blast_pindadss2", "Pindad SS2", "primary", "rifle"}
WEAPONS[114] = {"tfa_ins2_pkp", "PKP", "primary", "lmg"}
WEAPONS[115] = {"tfa_ins2_pm9", "PM-9", "secondary", "smg"}
WEAPONS[116] = {"tfa_fas2_ppbizon", "PP-19 Bizon", "primary", "smg"}
WEAPONS[117] = {"tfa_nam_ppsh41", "PPSH", "primary", "smg"}
WEAPONS[118] = {"tfa_ww2_pbz39", "PzB 39", "primary", "sniper"}
WEAPONS[119] = {"tfa_ins2_norinco_qbz97", "QBZ-97", "primary", "rifle"}
WEAPONS[120] = {"tfa_ins2_qsz92", "QSZ-92", "secondary", "pistol"}
WEAPONS[121] = {"yurie_eft_red_rebel_axe", "Red Rebel", "melee"}
WEAPONS[122] = {"tfa_ins2_remington_m870", "Remington M870", "primary", "shotgun"}
WEAPONS[123] = {"tfa_ins2_pd2_remington_msr", "Remington MSR", "primary", "sniper"}
WEAPONS[124] = {"tfa_ins2_rfb", "RFB", "primary", "rifle"}
WEAPONS[125] = {"swat_shield", "Riot Shield", "secondary", "melee"}
WEAPONS[126] = {"tfa_ins2_rpg7_scoped", "RPG-7", "primary", "explosive"}
WEAPONS[127] = {"tfa_ins2_rpk_74m", "RPK-74M", "primary", "lmg"}
WEAPONS[128] = {"tfa_ins2_s&w_500", "S&W 500", "secondary", "pistol"}
WEAPONS[129] = {"tfa_ins2_izh43sw", "Sawed Off", "secondary", "shotgun"}
WEAPONS[130] = {"tfa_ins2_scar_h_ssr", "SCAR-H", "primary", "rifle"}
WEAPONS[131] = {"tfa_ins2_sc_evo", "Scorpion Evo", "primary", "smg"}
WEAPONS[132] = {"tfa_l4d2_skorpion", "Skorpion", "secondary", "pistol"}
WEAPONS[133] = {"tfa_ins2_sks", "SKS", "primary", "rifle"}
WEAPONS[134] = {"tfa_ins2_spas12", "SPAS-12", "primary", "shotgun"}
WEAPONS[135] = {"tfa_ins2_spectre", "Spectre M4", "primary", "smg"}
WEAPONS[136] = {"tfa_ins2_saiga_spike", "Spike X1S", "primary", "sniper"}
WEAPONS[137] = {"tfa_ins2_sr25_eft", "SR-25", "primary", "rifle"}
WEAPONS[138] = {"tfa_ins2_sr2m_veresk", "SR-2M", "primary", "smg"}
WEAPONS[139] = {"tfa_doisten", "Sten", "primary", "smg"}
WEAPONS[140] = {"tfa_nam_stevens620", "Stevens 620", "primary", "shotgun"}
WEAPONS[141] = {"tfa_doistg44", "StG 44", "primary", "rifle"}
WEAPONS[142] = {"tfa_ins2_wpn_kacstoner", "Stoner LMG A1", "primary", "lmg"}
WEAPONS[143] = {"tfa_ins2_sv98", "SV-98", "primary", "sniper"}
WEAPONS[144] = {"tfa_ins2_warface_orsis_t5000", "T-5000", "primary", "sniper"}
WEAPONS[145] = {"tfa_japanese_exclusive_tanto", "Tanto", "melee"}
WEAPONS[146] = {"tfa_ins_sandstorm_tariq", "Tariq", "secondary", "pistol"}
WEAPONS[147] = {"st_stim_pistol", "TCo Stim Pistol", "secondary", "pistol"}
WEAPONS[148] = {"tfa_doithompsonm1928", "Thompson M1928", "primary", "smg"}
WEAPONS[149] = {"tfa_doithompsonm1a1", "Thompson M1A1", "primary", "smg"}
WEAPONS[150] = {"tfa_ins2_tridagger", "Tri-Dagger", "melee"}
WEAPONS[151] = {"tfa_ins2_typhoon12", "Typhoon F12", "primary", "shotgun"}
WEAPONS[152] = {"tfa_ins2_ump45", "UMP", "primary", "smg"}
WEAPONS[153] = {"tfa_ins2_usp_match", "USP", "secondary", "pistol"}
WEAPONS[154] = {"tfa_ins2_imi_uzi", "Uzi", "secondary", "smg"}
WEAPONS[155] = {"tfa_ins2_vhsd2", "VHS-D2", "primary", "rifle"}
WEAPONS[156] = {"tfa_ins2_wa2000", "WA-2000", "primary", "sniper"}
WEAPONS[157] = {"tfa_ins2_walther_p99", "Walther P99", "secondary", "pistol"}
WEAPONS[158] = {"tfa_doi_webley", "Webley", "secondary", "pistol"}
WEAPONS[159] = {"tfa_ins2_xm8", "XM8", "primary", "rifle"}

LEVELARRAY = {}
LEVELARRAY[1] = 750 -- +75 XP
LEVELARRAY[2] = 825
LEVELARRAY[3] = 900
LEVELARRAY[4] = 975
LEVELARRAY[5] = 1050
LEVELARRAY[6] = 1125
LEVELARRAY[7] = 1200
LEVELARRAY[8] = 1275
LEVELARRAY[9] = 1350
LEVELARRAY[10] = 1450 -- +100 XP
LEVELARRAY[11] = 1550
LEVELARRAY[12] = 1650
LEVELARRAY[13] = 1750
LEVELARRAY[14] = 1850
LEVELARRAY[15] = 1950
LEVELARRAY[16] = 2050
LEVELARRAY[17] = 2150
LEVELARRAY[18] = 2250
LEVELARRAY[19] = 2350
LEVELARRAY[20] = 2475 -- +125 XP
LEVELARRAY[21] = 2600
LEVELARRAY[22] = 2725
LEVELARRAY[23] = 2850
LEVELARRAY[24] = 2975
LEVELARRAY[25] = 3100
LEVELARRAY[26] = 3225
LEVELARRAY[27] = 3350
LEVELARRAY[28] = 3475
LEVELARRAY[29] = 3600
LEVELARRAY[30] = 3750 -- +150 XP
LEVELARRAY[31] = 3900
LEVELARRAY[32] = 4050
LEVELARRAY[33] = 4200
LEVELARRAY[34] = 4350
LEVELARRAY[35] = 4500
LEVELARRAY[36] = 4650
LEVELARRAY[37] = 4800
LEVELARRAY[38] = 4950
LEVELARRAY[39] = 5100
LEVELARRAY[40] = 5275 -- +175 XP
LEVELARRAY[41] = 5450
LEVELARRAY[42] = 5625
LEVELARRAY[43] = 5800
LEVELARRAY[44] = 5975
LEVELARRAY[45] = 6150
LEVELARRAY[46] = 6325
LEVELARRAY[47] = 6500
LEVELARRAY[48] = 6675
LEVELARRAY[49] = 6850
LEVELARRAY[50] = 7050 -- +200 XP
LEVELARRAY[51] = 7250
LEVELARRAY[52] = 7450
LEVELARRAY[53] = 7650
LEVELARRAY[54] = 7850
LEVELARRAY[55] = 8050
LEVELARRAY[56] = 8250
LEVELARRAY[57] = 8450
LEVELARRAY[58] = 8650
LEVELARRAY[59] = 8850
LEVELARRAY[60] = "prestige"

GEAR = {}
GEAR[1] = {"tfa_bo3_fists", "Fists", "models/weapons/bo3_melees/fists/w_fists.mdl", "default", "default", "default"}
GEAR[2] = {"tfa_km2000_knife", "KM-2000", "models/weapons/w_km2000_knife.mdl", "default", "default", "default"}
GEAR[3] = {"tfa_ararebo_bf1", "Mace", "models/weapons/w_ararebo.mdl", "default", "default", "default"}
GEAR[4] = {"tfa_japanese_exclusive_tanto", "Tanto", "models/weapons/w_tanto_knife.mdl", "default", "default", "default"}
GEAR[5] = {"yurie_eft_semin_push_dagger", "Dagger", "models/yurie/eft/weapons/world/push_dagger.mdl", "melee", 100, 45}
GEAR[6] = {"tfa_ins2_tridagger", "Tri-Dagger", "models/weapons/w_tridagger_dooktr.mdl", "melee", 200, 90}
GEAR[7] = {"tfa_ilopn_m9_phrobis", "M9 Bayonet", "models/weapons/w_knife_m9_phrobis.mdl", "melee", 300, 135}
GEAR[8] = {"tfa_bo3_bowiezm", "Bowie Knife", "models/weapons/bo3_melees/bowiezm/w_bowiezm.mdl", "melee", 400, 180}
GEAR[9] = {"yurie_eft_united_cutlery_m48_kukri", "Kukri", "models/yurie/eft/weapons/world/m48_kukri.mdl", "melee", 500, 225}
GEAR[10] = {"tfa_bo3_bowie", "Carver", "models/weapons/bo3_melees/bowie/w_bowie.mdl", "melee", 600, 315}
GEAR[11] = {"tfa_karambit", "Karambit", "models/weapons/w_knife_karambit.mdl", "melee", 700, 360}
GEAR[12] = {"tfa_bo3_butterfly", "Butterfly Knife", "models/weapons/bo3_melees/butterfly/w_butterfly.mdl", "melee", 800, 405}
GEAR[13] = {"tfa_bo3_nunchucks", "Nunchucks", "models/weapons/bo3_melees/nunchucks/w_nunchucks.mdl", "melee", 900, 450}
GEAR[14] = {"tfa_bo3_axe", "Fire Axe", "models/weapons/bo3_melees/axe/w_axe.mdl", "melee", 1000, 495}
GEAR[15] = {"yurie_eft_red_rebel_axe", "Red Rebel", "models/yurie/eft/weapons/world/dmm_rebel_adze_axe.mdl", "melee", 1100, 540}

MODELS = {}
MODELS[1] = {"models/player/Group03/male_02.mdl", "Male", "default", "default"}
MODELS[2] = {"models/player/Group03/female_02.mdl", "Female", "default", "default"}
MODELS[3] = {"models/player/Group01/male_03.mdl", "Casual Male", "default", "default"}
MODELS[4] = {"models/player/mossman.mdl", "Casual Female", "default", "default"}
MODELS[5] = {"models/player/Group03m/male_05.mdl", "Doctor", "default", "default"}
MODELS[6] = {"models/player/Group03m/female_06.mdl", "Nurse", "default", "default"}
MODELS[7] = {"models/player/barney.mdl", "Barney", "default", "default"}
MODELS[8] = {"models/player/kleiner.mdl", "Kleiner", "default", "default"}
MODELS[9] = {"models/player/Group01/male_07.mdl", "Male 07", "kills", 100}
MODELS[10] = {"models/buff.mdl", "Buff", "kills", 200}
MODELS[11] = {"models/player/alyx.mdl", "Alyx", "kills", 300}
MODELS[12] = {"models/player/hostage/hostage_04.mdl", "Scientist", "kills", 500}
MODELS[13] = {"models/dannio/pm/elonmusk.mdl", "X Man", "kills", 750}
MODELS[14] = {"models/player/gman_high.mdl", "GMan", "kills", 1000}
MODELS[15] = {"models/player/amir/amir_v2.mdl", "Amir", "kills", 1500}
MODELS[16] = {"models/player/p2_chell.mdl", "Chell", "kills", 2000}
MODELS[17] = {"models/sazuma/mahoraga.mdl", "Mahoraga", "kills", 2500}
MODELS[18] = {"models/player/leet.mdl", "Badass", "kills", 3000}
MODELS[19] = {"models/player/arctic.mdl", "Frozen", "streak", 5}
MODELS[20] = {"models/player/riot.mdl", "Riot", "streak", 10}
MODELS[21] = {"models/player/gasmask.mdl", "Hazard Suit", "streak", 15}
MODELS[22] = {"models/player/police.mdl", "Officer", "streak", 20}
MODELS[23] = {"models/player/combine_soldier_prisonguard.mdl", "Cobalt Soilder", "streak", 25}
MODELS[24] = {"models/walterwhite/playermodels/walterwhitechem.mdl", "Drug Dealer", "streak", 30}
MODELS[25] = {"models/halo2/spartan_red.mdl", "Red", "matches", 1}
MODELS[26] = {"models/bunny/doctor_house/Doctor_House.mdl", "House", "matches", 3}
MODELS[27] = {"models/Splinks/Hotline_Miami/Jacket/Drive/Player_jacket_Drive.mdl", "Drive", "matches", 5}
MODELS[28] = {"models/subtact/motoaki_tanigo/yagoo_pm.mdl", "Yagoo", "matches", 10}
MODELS[29] = {"models/konnie/asapgaming/modernwarfare/grinchghillie.mdl", "Grinch", "matches", 20}
MODELS[30] = {"models/dizcordum/fallen_set.mdl", "Fallen", "matches", 50}
MODELS[31] = {"models/player/murphmash/verbaleli_pm.mdl", "Outer Space", "matches", 75}
MODELS[32] = {"models/timbleweebs/azura/azura_cyberpunk_pm.mdl", "Ethereal", "matches", 100}
MODELS[33] = {"models/player/chimp/chimp.mdl", "Le Monk", "matches", 150}
MODELS[34] = {"models/gruchk/oc/cool_skeleton.mdl", "Bones", "matches", 200}
MODELS[35] = {"models/halo2/spartan_blue.mdl", "Blue", "wins", 1}
MODELS[36] = {"models/humans/group03/chemsuit.mdl", "Radioactive", "wins", 3}
MODELS[37] = {"models/COW MW22 Horangi/Horangi.mdl", "Horangi", "wins", 10}
MODELS[38] = {"models/dap_blood/playermodel/dap_blood.mdl", "V1", "wins", 20}
MODELS[39] = {"models/florian/comission/helljumper/helljumper.mdl", "Helljumper", "wins", 50}
MODELS[40] = {"models/player/zombie_fast.mdl", "Infected", "wins", 100}
MODELS[41] = {"models/paynamia/bms/gordon_survivor_player.mdl", "Gordon", "headshot", 125}
MODELS[42] = {"models/munch/mace/Mace.mdl", "Mace", "headshot", 250}
MODELS[43] = {"models/player/darky_m/rust/arctic_hazmat.mdl", "Arctic", "headshot", 450}
MODELS[44] = {"models/player/eft/shturman/eft_shturman/models/eft_shturman_pm.mdl", "Shturman", "headshot", 900}
MODELS[45] = {"models/player/darky_m/rust/scientist.mdl", "Cobalt", "smackdown", 40}
MODELS[46] = {"models/survivors/Payday3/Jacket_PM.mdl", "Jacket", "smackdown", 80}
MODELS[47] = {"models/titanfall2_playermodel/kanepm.mdl", "Kane", "smackdown", 160}
MODELS[48] = {"models/auditor/r6s/707/vigil/chr_707_vigil.mdl", "Vigil", "smackdown", 320}
MODELS[49] = {"models/player/combine_super_soldier.mdl", "Super Soilder", "clutch", 30}
MODELS[50] = {"models/patrickbateman/Playermodels/patrickbateman.mdl", "Bateman", "clutch", 60}
MODELS[51] = {"models/player/darky_m/rust/spacesuit.mdl", "Spacesuit", "clutch", 150}
MODELS[52] = {"models/us_airforce/jetpilot_usaf.mdl", "Pilot", "clutch", 300}
MODELS[53] = {"models/player/john_marston.mdl", "Martson", "longshot", 30}
MODELS[54] = {"models/player/darky_m/rust/hazmat.mdl", "Hazmat", "longshot", 60}
MODELS[55] = {"models/player/darky_m/rust/nomad.mdl", "Nomad", "longshot", 150}
MODELS[56] = {"models/mark2580/payday2/pd2_gs_elite_player.mdl", "Elite", "longshot", 300}
MODELS[57] = {"models/maxpayne3/ufe/ufepm.mdl", "UFE", "pointblank", 120}
MODELS[58] = {"models/starwarsbf1/Scoutrooper.mdl", "Scout", "pointblank", 240}
MODELS[59] = {"models/kyo/ghot.mdl", "Ghost", "pointblank", 480}
MODELS[60] = {"models/mark2580/payday2/pd2_cloaker_player.mdl", "Cloaker", "pointblank", 720}
MODELS[61] = {"models/Krueger_PlayerModel/Zaper/Krueger_Body.mdl", "Krueger", "killstreaks", 80}
MODELS[62] = {"models/player/tabspeasant.mdl", "Wobbler", "killstreaks", 160}
MODELS[63] = {"models/captainbigbutt/vocaloid/miku_classic.mdl", "Miku", "killstreaks", 320}
MODELS[64] = {"models/theboys/homelander.mdl", "Homelander", "killstreaks", 480}
MODELS[65] = {"models/player/voikanaa/snoop_dogg.mdl", "Snoop", "buzzkills", 60}
MODELS[66] = {"models/pacagma/humans/heroes/imc_hero_viper_player.mdl", "Viper", "buzzkills", 120}
MODELS[67] = {"models/auditor/titanfall2/cooper/chr_jackcooper.mdl", "Cooper", "buzzkills", 200}
MODELS[68] = {"models/auditor/re2/chr_hunk_pmrig.mdl", "Hunk", "buzzkills", 320}

CARDS = {}
CARDS[1] = {"cards/default/barrels.png", "Barrels", "", "default", "default"}
CARDS[2] = {"cards/default/carbon.png", "Carbon", "", "default", "default"}
CARDS[3] = {"cards/default/construct.png", "Construct", "", "default", "default"}
CARDS[4] = {"cards/default/flare.png", "Flare", "", "default", "default"}
CARDS[5] = {"cards/default/flattywood.png", "Fattywood", "", "default", "default"}
CARDS[6] = {"cards/default/grapple.png", "Grapple", "", "default", "default"}
CARDS[7] = {"cards/default/industry.png", "Industry", "", "default", "default"}
CARDS[8] = {"cards/default/monkey.png", "Le Monk", "", "default", "default"}
CARDS[9] = {"cards/default/overhead.png", "Overhead", "", "default", "default"}
CARDS[10] = {"cards/default/specops.png", "Spec Ops", "", "default", "default"}
CARDS[11] = {"cards/default/stargazing.png", "Stargazing", "", "default", "default"}
CARDS[12] = {"cards/default/strobe.png", "Strobe", "", "default", "default"}
CARDS[13] = {"cards/kills/kill50.png", "Pistoling", "", "kills", 50}
CARDS[14] = {"cards/kills/kill200.png", "Smoke", "", "kills", 200}
CARDS[15] = {"cards/kills/kill500.png", "Titan", "", "kills", 500}
CARDS[16] = {"cards/kills/kill1000.png", "Hardened", "", "kills", 1000}
CARDS[17] = {"cards/kills/kill2000.png", "Leader", "", "kills", 2000}
CARDS[18] = {"cards/kills/kill3000.png", "Specialist", "", "kills", 3000}
CARDS[19] = {"cards/kills/streak5.png", "Convoy", "", "streak", 5}
CARDS[20] = {"cards/kills/streak10.png", "Expedition", "", "streak", 10}
CARDS[21] = {"cards/kills/streak15.png", "On Fire", "", "streak", 15}
CARDS[22] = {"cards/kills/streak20.png", "Artillery", "", "streak", 20}
CARDS[23] = {"cards/kills/streak25.png", "Timed", "", "streak", 25}
CARDS[24] = {"cards/kills/streak30.png", "Nuclear", "", "streak", 30}
CARDS[25] = {"cards/kills/matches1.png", "Noob", "", "matches", 1}
CARDS[26] = {"cards/kills/matches5.png", "Luke Warm", "", "matches", 5}
CARDS[27] = {"cards/kills/matches20.png", "Utility", "", "matches", 20}
CARDS[28] = {"cards/kills/matches50.png", "Lurking", "", "matches", 50}
CARDS[29] = {"cards/kills/matches100.png", "Expert", "", "matches", 100}
CARDS[30] = {"cards/kills/matches200.png", "Complete", "", "matches", 200}
CARDS[31] = {"cards/kills/wins1.png", "Victor", "", "wins", 1}
CARDS[32] = {"cards/kills/wins3.png", "Finish Line", "", "wins", 3}
CARDS[33] = {"cards/kills/wins10.png", "Confetti", "", "wins", 10}
CARDS[34] = {"cards/kills/wins20.png", "Improving", "", "wins", 20}
CARDS[35] = {"cards/kills/wins50.png", "Red Carpet", "", "wins", 50}
CARDS[36] = {"cards/kills/wins100.png", "Proud", "", "wins", 100}
CARDS[37] = {"cards/accolades/headshot1.png", "Headshot", "", "headshot", 50}
CARDS[38] = {"cards/accolades/headshot2.png", "Hunter", "", "headshot", 100}
CARDS[39] = {"cards/accolades/headshot3.png", "Icon", "", "headshot", 200}
CARDS[40] = {"cards/accolades/headshot4.png", "NODs", "", "headshot", 400}
CARDS[41] = {"cards/accolades/smackdown1.png", "Karambit", "", "smackdown", 25}
CARDS[42] = {"cards/accolades/smackdown2.png", "Samuri", "", "smackdown", 50}
CARDS[43] = {"cards/accolades/smackdown3.png", "Beach", "", "smackdown", 100}
CARDS[44] = {"cards/accolades/smackdown4.png", "Execution", "", "smackdown", 200}
CARDS[45] = {"cards/accolades/clutch1.png", "Deagle", "", "clutch", 30}
CARDS[46] = {"cards/accolades/clutch2.png", "Magnum", "", "clutch", 60}
CARDS[47] = {"cards/accolades/clutch3.png", "KRISS", "", "clutch", 100}
CARDS[48] = {"cards/accolades/clutch4.png", "FN", "", "clutch", 180}
CARDS[49] = {"cards/accolades/longshot1.png", "Downhill", "", "longshot", 30}
CARDS[50] = {"cards/accolades/longshot2.png", "Stalker", "", "longshot", 60}
CARDS[51] = {"cards/accolades/longshot3.png", "Highrise", "", "longshot", 100}
CARDS[52] = {"cards/accolades/longshot4.png", "Tactical", "", "longshot", 180}
CARDS[53] = {"cards/accolades/pointblank1.png", "Showers", "", "pointblank", 45}
CARDS[54] = {"cards/accolades/pointblank2.png", "Full Auto", "", "pointblank", 90}
CARDS[55] = {"cards/accolades/pointblank3.png", "Live Fire", "", "pointblank", 150}
CARDS[56] = {"cards/accolades/pointblank4.png", "Dual Wield", "", "pointblank", 275}
CARDS[57] = {"cards/accolades/killstreaks1.png", "Soilder", "", "killstreaks", 40}
CARDS[58] = {"cards/accolades/killstreaks2.png", "Badass", "", "killstreaks", 90}
CARDS[59] = {"cards/accolades/killstreaks3.png", "Skulls", "", "killstreaks", 160}
CARDS[60] = {"cards/accolades/killstreaks4.png", "Radiation", "", "killstreaks", 270}
CARDS[61] = {"cards/accolades/buzzkills1.png", "Wobblers", "", "buzzkills", 40}
CARDS[62] = {"cards/accolades/buzzkills2.png", "POV", "", "buzzkills", 90}
CARDS[63] = {"cards/accolades/buzzkills3.png", "Preperation", "", "buzzkills", 160}
CARDS[64] = {"cards/accolades/buzzkills4.png", "Twin Flame", "", "buzzkills", 270}
CARDS[65] = {"cards/color/red.png", "Red", "Solid red color", "color", "color"}
CARDS[66] = {"cards/color/orange.png", "Orange", "Solid orange color", "color", "color"}
CARDS[67] = {"cards/color/yellow.png", "Yellow", "Solid yellow color", "color", "color"}
CARDS[68] = {"cards/color/lime.png", "Lime", "Solid lime color", "color", "color"}
CARDS[69] = {"cards/color/cyan.png", "Cyan", "Solid cyan color", "color", "color"}
CARDS[70] = {"cards/color/blue.png", "Blue", "Solid blue color", "color", "color"}
CARDS[71] = {"cards/color/purple.png", "Purple", "Solid magenta color", "color", "color"}
CARDS[72] = {"cards/color/pink.png", "Pink", "Solid pink color", "color", "color"}
CARDS[73] = {"cards/color/brown.png", "Brown", "Solid brown color", "color", "color"}
CARDS[74] = {"cards/color/gray.png", "Gray", "Solid gray color", "color", "color"}
CARDS[75] = {"cards/color/white.png", "White", "Solid white color", "color", "color"}
CARDS[76] = {"cards/color/black.png", "Black", "Solid black color", "color", "color"}
CARDS[77] = {"cards/mastery/aa12.png", "Close Up", "AA-12 mastery", "mastery", "tfa_ins2_aa12"}
CARDS[78] = {"cards/mastery/acr.png", "Posted Up", "ACR mastery", "mastery", "tfa_ins2_acrc"}
CARDS[79] = {"cards/mastery/aek971.png", "Stalker", "AEK-971 mastery", "mastery", "tfa_ins2_aek971"}
CARDS[80] = {"cards/mastery/ak12.png", "Inspection", "AK-12 mastery", "mastery", "tfa_ins2_ak12"}
CARDS[81] = {"cards/mastery/ak400.png", "Overhead", "AK-400 mastery", "mastery", "tfa_ins2_ak400"}
CARDS[82] = {"cards/mastery/ak47.png", "Sunset", "AK-47 mastery", "mastery", "tfa_ins2_akms"}
CARDS[83] = {"cards/mastery/aks74u.png", "Loaded", "AKS-74U mastery", "mastery", "tfa_ins2_aks_r"}
CARDS[84] = {"cards/mastery/american180.png", "Tangerine", "American-180 mastery", "mastery", "tfa_cold_war_american180"}
CARDS[85] = {"cards/mastery/an94.png", "Hijacked", "AN-94 mastery", "mastery", "tfa_ins2_abakan"}
CARDS[86] = {"cards/mastery/ar57.png", "Ghost", "AR-57 mastery", "mastery", "tfa_ins2_ar57"}
CARDS[87] = {"cards/mastery/asval.png", "Obesa", "AS-VAL mastery", "mastery", "tfa_inss_asval"}
CARDS[88] = {"cards/mastery/ash12.png", "Interstellar", "ASh-12 mastery", "mastery", "tfa_pd2_ash12"}
CARDS[89] = {"cards/mastery/auga2.png", "Lightning", "AUG A2 mastery", "mastery", "tfa_fml_csgo_aug"}
CARDS[90] = {"cards/mastery/avt40.png", "Embers", "AVT-40 mastery", "mastery", "tfa_ins2_wpn_avt40"}
CARDS[91] = {"cards/mastery/awm.png", "Dust II", "AWM mastery", "mastery", "tfa_cod_accuracy_international_l115a3"}
CARDS[92] = {"cards/mastery/ax308.png", "Range", "AX-308 mastery", "mastery", "tfa_ins2_warface_ax308"}
CARDS[93] = {"cards/mastery/barrettm98b.png", "Ready", "Barrett M98B mastery", "mastery", "tfa_ins2_barrett_m98_bravo"}
CARDS[94] = {"cards/mastery/berettamx4.png", "House", "Barrett Mx4 mastery", "mastery", "tfa_ins2_mx4"}
CARDS[95] = {"cards/mastery/bow.png", "Cargo Ship", "Bow mastery", "mastery", "rust_bow"}
CARDS[96] = {"cards/mastery/bowieknife.png", "Zombie", "Bowie Knife mastery", "mastery", "tfa_bo3_bowiezm"}
CARDS[97] = {"cards/mastery/br99.png", "Rouge", "BR99 mastery", "mastery", "tfa_ins2_br99"}
CARDS[98] = {"cards/mastery/bren.png", "Flank", "Bren mastery", "mastery", "tfa_doibren"}
CARDS[99] = {"cards/mastery/butterfly.png", "Bliss", "Butterfly Knife mastery", "mastery", "tfa_bo3_butterfly"}
CARDS[100] = {"cards/mastery/carver.png", "Fungal", "Carver mastery", "mastery", "tfa_bo3_bowie"}
CARDS[101] = {"cards/mastery/colt9mm.png", "Magazines", "Colt 9mm mastery", "mastery", "tfa_ins2_m4_9mm"}
CARDS[102] = {"cards/mastery/coonan.png", "Strip", "Coonan .357 mastery", "mastery", "tfa_coonan_357"}
CARDS[103] = {"cards/mastery/crossbow.png", "Arrows", "Crossbow mastery", "mastery", "rust_crossbow"}
CARDS[104] = {"cards/mastery/cz75.png", "Nuke", "CZ 75 mastery", "mastery", "tfa_ins2_cz75"}
CARDS[105] = {"cards/mastery/cz805.png", "Showcase", "CZ 805 mastery", "mastery", "tfa_ins2_cz805"}
CARDS[106] = {"cards/mastery/dagger.png", "Fish", "Dagger mastery", "mastery", "yurie_eft_semin_push_dagger"}
CARDS[107] = {"cards/mastery/deserteagle.png", "Mag Check", "Desert Eagle mastery", "mastery", "tfa_ins2_deagle"}
CARDS[108] = {"cards/mastery/dsr50.png", "Arena", "DSR-50 mastery", "mastery", "tfa_ins2_warface_amp_dsr1"}
CARDS[109] = {"cards/mastery/dualmac.png", "Lars", "Dual Mac 10s mastery", "mastery", "tfa_dualmac"}
CARDS[110] = {"cards/mastery/dualskorpion.png", "Celestial", "Dual Skorpions mastery", "mastery", "tfa_l4d2_skorpion_dual"}
CARDS[111] = {"cards/mastery/famas.png", "Siege", "Famas mastery", "mastery", "tfa_ins2_famas"}
CARDS[112] = {"cards/mastery/fg42.png", "Glint", "FG 42 mastery", "mastery", "tfa_doifg42"}
CARDS[113] = {"cards/mastery/fireaxe.png", "Sunrise", "Fire Axe mastery", "mastery", "tfa_bo3_axe"}
CARDS[114] = {"cards/mastery/fists.png", "Blood", "Fists mastery", "mastery", "tfa_bo3_fists"}
CARDS[115] = {"cards/mastery/fiveseven.png", "Galactic", "Fiveseven mastery", "mastery", "tfa_ins2_fiveseven_eft"}
CARDS[116] = {"cards/mastery/flamethrower.png", "Haze", "Flamethrower mastery", "mastery", "tfa_codww2_flamethrower"}
CARDS[117] = {"cards/mastery/fn2000.png", "Armory", "FN 2000 mastery", "mastery", "tfa_ins2_fn_2000"}
CARDS[118] = {"cards/mastery/fnfal.png", "Exposed", "FN FAL mastery", "mastery", "tfa_ins2_fn_fal"}
CARDS[119] = {"cards/mastery/fnp45.png", "ACP", "FNP-45 mastery", "mastery", "tfa_ins2_fnp45"}
CARDS[120] = {"cards/mastery/g28.png", "Legacy", "G28 mastery", "mastery", "tfa_ins2_g28"}
CARDS[121] = {"cards/mastery/g36a1.png", "Aimpoint", "G36A1 mastery", "mastery", "tfa_ins2_g36a1"}
CARDS[122] = {"cards/mastery/g3a3.png", "Crane", "G3A3 mastery", "mastery", "tfa_ins2_wpn_g3a3"}
CARDS[123] = {"cards/mastery/galil.png", "Ring", "Galil mastery", "mastery", "tfa_ins2_wpn_imigalilarm"}
CARDS[124] = {"cards/mastery/glock18.png", "Ospery", "Glock 18 mastery", "mastery", "tfa_glk_gen4"}
CARDS[125] = {"cards/mastery/grenade.png", "Quasar", "Grenade mastery", "mastery", "grenade"}
CARDS[126] = {"cards/mastery/groza.png", "Bullpup", "Groza mastery", "mastery", "tfa_ins2_groza"}
CARDS[127] = {"cards/mastery/gsh18.png", "Skyscraper", "GSH-18 mastery", "mastery", "tfa_ins2_gsh18"}
CARDS[128] = {"cards/mastery/hk416.png", "Infinite", "HK416 mastery", "mastery", "tfa_ins2_hk416"}
CARDS[129] = {"cards/mastery/hk53.png", "Chains", "HK53 mastery", "mastery", "tfa_ins2_fml_hk53"}
CARDS[130] = {"cards/mastery/honeybadger.png", "Business", "Honey Badger mastery", "mastery", "tfa_ins2_cq300"}
CARDS[131] = {"cards/mastery/howatype64.png", "Cradle", "Howa Type 64 mastery", "mastery", "tfa_howa_type_64"}
CARDS[132] = {"cards/mastery/imbelia2.png", "Process", "Imbel IA2 mastery", "mastery", "tfa_ins2_imbelia2"}
CARDS[133] = {"cards/mastery/intervention.png", "Trickshot", "Intervention mastery", "mastery", "tfa_ins2_warface_cheytac_m200"}
CARDS[134] = {"cards/mastery/kacchainsaw.png", "Scare", "KAC ChainSAW mastery", "mastery", "ryry_tfa_chainsaw"}
CARDS[135] = {"cards/mastery/kar98k.png", "Empire", "Kar98k mastery", "mastery", "tfa_doi_kar98k"}
CARDS[136] = {"cards/mastery/karambit.png", "Shoreline", "Karambit mastery", "mastery", "tfa_karambit"}
CARDS[137] = {"cards/mastery/km2000.png", "Flatgrass", "KM-2000 mastery", "mastery", "tfa_km2000_knife"}
CARDS[138] = {"cards/mastery/krissvector.png", "Narkotica", "KRISS Vector mastery", "mastery", "tfa_ins2_krissv"}
CARDS[139] = {"cards/mastery/ks23.png", "Vintage", "KS-23 mastery", "mastery", "tfa_coldwar_ks23"}
CARDS[140] = {"cards/mastery/ksg.png", "Flames", "KSG mastery", "mastery", "tfa_ins2_ksg"}
CARDS[141] = {"cards/mastery/kukri.png", "Peace", "Kukri mastery", "mastery", "yurie_eft_united_cutlery_m48_kukri"}
CARDS[142] = {"cards/mastery/l85.png", "Groves", "L85 mastery", "mastery", "tfa_ins2_l85a2"}
CARDS[143] = {"cards/mastery/leeenfield.png", "Minecraft", "Lee Enfield master", "mastery", "tfa_doi_enfield"}
CARDS[144] = {"cards/mastery/lewis.png", "Big Bang", "Lewis Gun mastery", "mastery", "tfa_doilewis"}
CARDS[145] = {"cards/mastery/lr300.png", "Oil Rig", "LR-300 mastery", "mastery", "tfa_ins2_zm_lr300"}
CARDS[146] = {"cards/mastery/m1garand.png", "Underworld", "M1 Garand mastery", "mastery", "tfa_doi_garand"}
CARDS[147] = {"cards/mastery/minigun.png", "SYS.//", "M134 Minigun mastery", "mastery", "tfa_usurper"}
CARDS[148] = {"cards/mastery/m14.png", "Bridge", "M14 mastery", "mastery", "tfa_ins2_m14retro"}
CARDS[149] = {"cards/mastery/m1911.png", "Relic", "M1911 mastery", "mastery", "tfa_nam_m1911"}
CARDS[150] = {"cards/mastery/m1918.png", "Bipod", "M1918 mastery", "mastery", "tfa_doim1918"}
CARDS[151] = {"cards/mastery/m1919.png", "Customs", "M1919 mastery", "mastery", "tfa_doim1919"}
CARDS[152] = {"cards/mastery/m249.png", "Camper", "M249 mastery", "mastery", "tfa_ins2_minimi"}
CARDS[153] = {"cards/mastery/m3grease.png", "Grease", "M3 Grease Gun mastery", "mastery", "tfa_doim3greasegun"}
CARDS[154] = {"cards/mastery/m45a1.png", "Legend", "M45A1 mastery", "mastery", "tfa_ins2_colt_m45"}
CARDS[155] = {"cards/mastery/m4a1.png", "Smug", "M4A1 mastery", "mastery", "tfa_ins2_eftm4a1"}
CARDS[156] = {"cards/mastery/m79.png", "Cool With It", "M79 mastery", "mastery", "tfa_nam_m79"}
CARDS[157] = {"cards/mastery/m9.png", "Full Metal", "M9 mastery", "mastery", "tfa_ins2_m9"}
CARDS[158] = {"cards/mastery/m9bayonet.png", "Park", "M9 Bayonet mastery", "mastery", "tfa_ilopn_m9_phrobis"}
CARDS[159] = {"cards/mastery/mac10.png", "Dev", "Mac 10 mastery", "mastery", "bocw_mac10_alt"}
CARDS[160] = {"cards/mastery/mace.png", "Industry", "Mace master", "mastery", "tfa_ararebo_bf1"}
CARDS[161] = {"cards/mastery/makarov.png", "Leaves", "Makarov mastery", "mastery", "tfa_ins2_pm"}
CARDS[162] = {"cards/mastery/maresleg.png", "High Optic", "Mare's Leg mastery", "mastery", "tfa_tfre_maresleg"}
CARDS[163] = {"cards/mastery/mas38.png", "Galaxy", "Mas 38 mastery", "mastery", "tfa_fml_lefrench_mas38"}
CARDS[164] = {"cards/mastery/mg34.png", "Heavy ", "MG 34 mastery", "mastery", "tfa_doimg34"}
CARDS[165] = {"cards/mastery/mg42.png", "D-Day", "MG 42 mastery", "mastery", "tfa_doimg42"}
CARDS[166] = {"cards/mastery/mk14ebr.png", "Prepared", "MK 14 EBR mastery", "mastery", "tfa_ins2_mk14ebr"}
CARDS[167] = {"cards/mastery/mk23.png", "Uranium", "MK 23 mastery", "mastery", "tfa_ins2_mk23"}
CARDS[168] = {"cards/mastery/mk18.png", "Waster", "MK18 mastery", "mastery", "tfa_fml_inss_mk18"}
CARDS[169] = {"cards/mastery/model10.png", "Walter", "Model 10 mastery", "mastery", "tfa_ins2_swmodel10"}
CARDS[170] = {"cards/mastery/mosin.png", "Rebirth", "Mosin Nagant mastery", "mastery", "tfa_ins2_mosin_nagant"}
CARDS[171] = {"cards/mastery/mp40.png", "Reflection", "MP 40 mastery", "mastery", "tfa_doimp40"}
CARDS[172] = {"cards/mastery/mp443.png", "Bush", "MP-443 mastery", "mastery", "tfa_ins2_mp443"}
CARDS[173] = {"cards/mastery/mp18.png", "Modern", "MP18 mastery", "mastery", "tfa_ww1_mp18"}
CARDS[174] = {"cards/mastery/mp5.png", "Select", "MP5 mastery", "mastery", "tfa_inss2_hk_mp5a5"}
CARDS[175] = {"cards/mastery/mp5k.png", "H&K", "MP5K mastery", "mastery", "tfa_ins2_mp5k"}
CARDS[176] = {"cards/mastery/mp7.png", "Oilspill", "MP7 mastery", "mastery", "tfa_ins2_mp7"}
CARDS[177] = {"cards/mastery/mp9.png", "Training", "MP9 mastery", "mastery", "tfa_ins2_warface_bt_mp9"}
CARDS[178] = {"cards/mastery/mpx.png", "Waterfall", "MPX mastery", "mastery", "tfa_jw_tti_mpx"}
CARDS[179] = {"cards/mastery/mr96.png", "Polish", "MR-96 mastery", "mastery", "tfa_ins2_mr96"}
CARDS[180] = {"cards/mastery/mts225.png", "Slug", "MTs225 mastery", "mastery", "tfa_ins2_mc255"}
CARDS[181] = {"cards/mastery/nailgun.png", "Nails", "Nailgun mastery", "mastery", "tfa_bocw_nailgun"}
CARDS[182] = {"cards/mastery/nova.png", "Dark Street", "Nova mastery", "mastery", "tfa_ins2_nova"}
CARDS[183] = {"cards/mastery/nunchucks.png", "Yin", "Nunchucks mastery", "mastery", "tfa_bo3_nunchucks"}
CARDS[184] = {"cards/mastery/osp18.png", "Irons", "OSP-18 mastery", "mastery", "tfa_l4d2_osp18"}
CARDS[185] = {"cards/mastery/otspernach.png", "Speedloader", "OTs-33 Pernach mastery", "mastery", "tfa_ins2_ots_33_pernach"}
CARDS[186] = {"cards/mastery/owenmki.png", "Grid", "Owen Gun mastery", "mastery", "tfa_doiowen"}
CARDS[187] = {"cards/mastery/p320.png", "Sauer", "P320 mastery", "mastery", "tfa_ins2_p320_m18"}
CARDS[188] = {"cards/mastery/p90.png", "MISSING", "P90 mastery", "mastery", "tfa_fml_p90_tac"}
CARDS[189] = {"cards/mastery/pindad.png", "Labs", "Pindad SS2 mastery", "mastery", "tfa_blast_pindadss2"}
CARDS[190] = {"cards/mastery/pkp.png", "Royalty", "PKP mastery", "mastery", "tfa_ins2_pkp"}
CARDS[191] = {"cards/mastery/pm9.png", "Akimbo", "PM-9 mastery", "mastery", "tfa_ins2_pm9"}
CARDS[192] = {"cards/mastery/ppbizon.png", "Rainbow", "PP-19 Bizon mastery", "mastery", "tfa_fas2_ppbizon"}
CARDS[193] = {"cards/mastery/ppsh.png", "Mephitic", "PPSH mastery", "mastery", "tfa_nam_ppsh41"}
CARDS[194] = {"cards/mastery/pzb39.png", "Exotic", "PzB 39 mastery", "mastery", "tfa_ww2_pbz39"}
CARDS[195] = {"cards/mastery/qbz97.png", "Hideout", "QBZ-97 mastery", "mastery", "tfa_ins2_norinco_qbz97"}
CARDS[196] = {"cards/mastery/qsz92.png", "yippee", "QSZ-92 mastery", "mastery", "tfa_ins2_qsz92"}
CARDS[197] = {"cards/mastery/redrebel.png", "Tagilla", "Red Rebel mastery", "mastery", "yurie_eft_red_rebel_axe"}
CARDS[198] = {"cards/mastery/remingtonm870.png", "Code", "Remington M870 master", "mastery", "tfa_ins2_remington_m870"}
CARDS[199] = {"cards/mastery/remingtonmsr.png", "Lightshow", "Remington MSR mastery", "mastery", "tfa_ins2_pd2_remington_msr"}
CARDS[200] = {"cards/mastery/rfb.png", "Extraction", "RFB mastery", "mastery", "tfa_ins2_rfb"}
CARDS[201] = {"cards/mastery/rpg7.png", "Damascus", "RPG-7 mastery", "mastery", "tfa_ins2_rpg7_scoped"}
CARDS[202] = {"cards/mastery/rpk74m.png", "Elcan", "RPK-74M mastery", "mastery", "tfa_ins2_rpk_74m"}
CARDS[203] = {"cards/mastery/sw500.png", "Companion", "S&W 500 mastery", "mastery", "tfa_ins2_s&w_500"}
CARDS[204] = {"cards/mastery/sawedoff.png", "Halves", "Sawed Off mastery", "mastery", "tfa_ins2_izh43sw"}
CARDS[205] = {"cards/mastery/scarh.png", "Tilted", "SCAR-H mastery", "mastery", "tfa_ins2_scar_h_ssr"}
CARDS[206] = {"cards/mastery/scorpionevo.png", "Raid", "Scorpion Evo mastery", "mastery", "tfa_ins2_sc_evo"}
CARDS[207] = {"cards/mastery/skorpion.png", "Black Hole", "Skorpion mastery", "mastery", "tfa_l4d2_skorpion"}
CARDS[208] = {"cards/mastery/sks.png", "Scav", "SKS mastery", "mastery", "tfa_ins2_sks"}
CARDS[209] = {"cards/mastery/spas.png", "12 Gauge", "SPAS-12 mastery", "mastery", "tfa_ins2_spas12"}
CARDS[210] = {"cards/mastery/spectrem4.png", "Mall", "Spectre M4 mastery", "mastery", "tfa_ins2_spectre"}
CARDS[211] = {"cards/mastery/spikex1s.png", "Prototype", "Spike X1S mastery", "mastery", "tfa_ins2_saiga_spike"}
CARDS[212] = {"cards/mastery/sr25.png", "D2", "SR-25 mastery", "mastery", "tfa_ins2_sr25_eft"}
CARDS[213] = {"cards/mastery/sr2m.png", "Blueprint", "SR-2M mastery", "mastery", "tfa_ins2_sr2m_veresk"}
CARDS[214] = {"cards/mastery/sten.png", "Lens Flare", "Sten mastery", "mastery", "tfa_doisten"}
CARDS[215] = {"cards/mastery/stevens620.png", "Mod", "Stevens 620 mastery", "mastery", "tfa_nam_stevens620"}
CARDS[216] = {"cards/mastery/stg44.png", "Wood", "StG 44 mastery", "mastery", "tfa_doistg44"}
CARDS[217] = {"cards/mastery/stonerlmg.png", "Stoner", "Stoner LMG A1 mastery", "mastery", "tfa_ins2_wpn_kacstoner"}
CARDS[218] = {"cards/mastery/sv98.png", "Vertigo", "SV-98 mastery", "mastery", "tfa_ins2_sv98"}
CARDS[219] = {"cards/mastery/t5000.png", "Reserve", "T-5000 mastery", "mastery", "tfa_ins2_warface_orsis_t5000"}
CARDS[220] = {"cards/mastery/tanto.png", "Shipment", "Tanto mastery", "mastery", "tfa_japanese_exclusive_tanto"}
CARDS[221] = {"cards/mastery/tariq.png", "Dog", "Tariq mastery", "mastery", "tfa_ins_sandstorm_tariq"}
CARDS[222] = {"cards/mastery/thompsonm1928.png", "Typewritter", "Thompson M1928 master", "mastery", "tfa_doithompsonm1928"}
CARDS[223] = {"cards/mastery/thompson.png", "Depression", "Thompson M1A1 master", "mastery", "tfa_doithompsonm1a1"}
CARDS[224] = {"cards/mastery/tridagger.png", "Daggers", "Tri-Dagger mastery", "mastery", "tfa_ins2_tridagger"}
CARDS[225] = {"cards/mastery/typhoonf12.png", "Ultrakill", "Typhoon F12 mastery", "mastery", "tfa_ins2_typhoon12"}
CARDS[226] = {"cards/mastery/ump.png", "Nuketown", "UMP mastery", "mastery", "tfa_ins2_ump45"}
CARDS[227] = {"cards/mastery/usp.png", "Strike", "USP mastery", "mastery", "tfa_ins2_usp_match"}
CARDS[228] = {"cards/mastery/uzi.png", "Alpha", "Uzi mastery", "mastery", "tfa_ins2_imi_uzi"}
CARDS[229] = {"cards/mastery/vhsd2.png", "Liminal", "VHS-D2 mastery", "mastery", "tfa_ins2_vhsd2"}
CARDS[230] = {"cards/mastery/wa2000.png", "Brain", "WA-2000 mastery", "mastery", "tfa_ins2_wa2000"}
CARDS[231] = {"cards/mastery/waltherp99.png", "Advisory", "Walther P99 mastery", "mastery", "tfa_ins2_walther_p99"}
CARDS[232] = {"cards/mastery/webley.png", "Bear", "Webley mastery", "mastery", "tfa_doi_webley"}
CARDS[233] = {"cards/mastery/xm8.png", "Ragdoll", "XM8 mastery", "mastery", "tfa_ins2_xm8"}
CARDS[234] = {"cards/leveling/5.png", "Mist", "Prestige 0 Level 5", "level", 5}
CARDS[235] = {"cards/leveling/10.png", "Tech", "Prestige 0 Level 10", "level", 10}
CARDS[236] = {"cards/leveling/15.png", "Processing", "Prestige 0 Level 15", "level", 15}
CARDS[237] = {"cards/leveling/20.png", "Monolith", "Prestige 0 Level 20", "level", 20}
CARDS[238] = {"cards/leveling/25.png", "Kitty", "Prestige 0 Level 25", "level", 25}
CARDS[239] = {"cards/leveling/30.png", "Tonal", "Prestige 0 Level 30", "level", 30}
CARDS[240] = {"cards/leveling/35.png", "Gangster", "Prestige 0 Level 35", "level", 35}
CARDS[241] = {"cards/leveling/40.png", "Shark", "Prestige 0 Level 40", "level", 40}
CARDS[242] = {"cards/leveling/45.png", "Bath", "Prestige 0 Level 45", "level", 45}
CARDS[243] = {"cards/leveling/50.png", "Rig", "Prestige 0 Level 50", "level", 50}
CARDS[244] = {"cards/leveling/55.png", "Station", "Prestige 0 Level 55", "level", 55}
CARDS[245] = {"cards/leveling/60.png", "Scenic", "Prestige 0 Level 60", "level", 60}
CARDS[246] = {"cards/leveling/65.png", "Dunes", "Prestige 1 Level 5", "level", 65}
CARDS[247] = {"cards/leveling/70.png", "Pyro", "Prestige 1 Level 10", "level", 70}
CARDS[248] = {"cards/leveling/75.png", "Toxicity", "Prestige 1 Level 15", "level", 75}
CARDS[249] = {"cards/leveling/80.png", "Drainer", "Prestige 1 Level 20", "level", 80}
CARDS[250] = {"cards/leveling/85.png", "Aquarium", "Prestige 1 Level 25", "level", 85}
CARDS[251] = {"cards/leveling/90.png", "Drive", "Prestige 1 Level 30", "level", 90}
CARDS[252] = {"cards/leveling/95.png", "Nightfall", "Prestige 1 Level 35", "level", 95}
CARDS[253] = {"cards/leveling/100.png", "Thunder", "Prestige 1 Level 40", "level", 100}
CARDS[254] = {"cards/leveling/105.png", "Shift", "Prestige 1 Level 45", "level", 105}
CARDS[255] = {"cards/leveling/110.png", "Horizon", "Prestige 1 Level 50", "level", 110}
CARDS[256] = {"cards/leveling/115.png", "Summit", "Prestige 1 Level 55", "level", 115}
CARDS[257] = {"cards/leveling/120.png", "Illusion", "Prestige 1 Level 60", "level", 120}
CARDS[258] = {"cards/leveling/125.png", "Stare", "Prestige 2 Level 5", "level", 125}
CARDS[259] = {"cards/leveling/130.png", "Death", "Prestige 2 Level 10", "level", 130}
CARDS[260] = {"cards/leveling/135.png", "Man", "Prestige 2 Level 15", "level", 135}
CARDS[261] = {"cards/leveling/140.png", "Depths", "Prestige 2 Level 20", "level", 140}
CARDS[262] = {"cards/leveling/145.png", "Irony", "Prestige 2 Level 25", "level", 145}
CARDS[263] = {"cards/leveling/150.png", "Grass", "Prestige 2 Level 30", "level", 150}
CARDS[264] = {"cards/leveling/155.png", "Scott Up", "Prestige 2 Level 35", "level", 155}
CARDS[265] = {"cards/leveling/160.png", "Buzzkilled", "Prestige 2 Level 40", "level", 160}
CARDS[266] = {"cards/leveling/165.png", "Fumos", "Prestige 2 Level 45", "level", 165}
CARDS[267] = {"cards/leveling/170.png", "The Voices", "Prestige 2 Level 50", "level", 170}
CARDS[268] = {"cards/leveling/175.png", "Crisis", "Prestige 2 Level 55", "level", 175}
CARDS[269] = {"cards/leveling/180.png", "CRT", "Prestige 2 Level 60", "level", 180}
CARDS[270] = {"cards/leveling/185.png", "Operative", "Prestige 3 Level 5", "level", 185}
CARDS[271] = {"cards/leveling/190.png", "Cool Skull", "Prestige 3 Level 10", "level", 190}
CARDS[272] = {"cards/leveling/195.png", "Breakcore", "Prestige 3 Level 15", "level", 195}
CARDS[273] = {"cards/leveling/200.png", "Dr. Han", "Prestige 3 Level 20", "level", 200}
CARDS[274] = {"cards/leveling/205.png", "Waves", "Prestige 3 Level 25", "level", 205}
CARDS[275] = {"cards/leveling/210.png", "Universe", "Prestige 3 Level 30", "level", 210}
CARDS[276] = {"cards/leveling/215.png", "Invasion", "Prestige 3 Level 35", "level", 215}
CARDS[277] = {"cards/leveling/220.png", "Airship", "Prestige 3 Level 40", "level", 220}
CARDS[278] = {"cards/leveling/225.png", "Darkness", "Prestige 3 Level 45", "level", 225}
CARDS[279] = {"cards/leveling/230.png", "Arctic", "Prestige 3 Level 50", "level", 230}
CARDS[280] = {"cards/leveling/235.png", "Modern", "Prestige 3 Level 55", "level", 235}
CARDS[281] = {"cards/leveling/240.png", "Childhood", "Prestige 3 Level 60", "level", 240}
CARDS[282] = {"cards/leveling/245.png", "Strive", "Prestige 4 Level 5", "level", 245}
CARDS[283] = {"cards/leveling/250.png", "Lilypad", "Prestige 4 Level 10", "level", 250}
CARDS[284] = {"cards/leveling/255.png", "Prickly", "Prestige 4 Level 15", "level", 255}
CARDS[285] = {"cards/leveling/260.png", "Strawberry", "Prestige 4 Level 20", "level", 260}
CARDS[286] = {"cards/leveling/265.png", "Kiwi", "Prestige 4 Level 25", "level", 265}
CARDS[287] = {"cards/leveling/270.png", "Banana", "Prestige 4 Level 30", "level", 270}
CARDS[288] = {"cards/leveling/275.png", "Bunnies", "Prestige 4 Level 35", "level", 275}
CARDS[289] = {"cards/leveling/280.png", "Kitties", "Prestige 4 Level 40", "level", 280}
CARDS[290] = {"cards/leveling/285.png", "Puppies", "Prestige 4 Level 45", "level", 285}
CARDS[291] = {"cards/leveling/290.png", "Totem", "Prestige 4 Level 50", "level", 290}
CARDS[292] = {"cards/leveling/295.png", "View", "Prestige 4 Level 55", "level", 295}
CARDS[293] = {"cards/leveling/300.png", "Ruins", "Prestige 4 Level 60", "level", 300}
CARDS[294] = {"cards/pride/pride.png", "Pride", "<3", "pride", "pride"}
CARDS[295] = {"cards/pride/bi.png", "Bi", "<3", "pride", "pride"}
CARDS[296] = {"cards/pride/pan.png", "Pan", "<3", "pride", "pride"}
CARDS[297] = {"cards/pride/gay.png", "Gay", "<3", "pride", "pride"}
CARDS[298] = {"cards/pride/lesbian.png", "Lesbian", "<3", "pride", "pride"}
CARDS[299] = {"cards/pride/ace.png", "Ace", "<3", "pride", "pride"}
CARDS[300] = {"cards/pride/trans.png", "Trans", "<3", "pride", "pride"}
CARDS[301] = {"cards/pride/genderfluid.png", "Gen. Fluid", "<3", "pride", "pride"}
CARDS[302] = {"cards/pride/genderqueer.png", "Gen. Queer", "<3", "pride", "pride"}
CARDS[303] = {"cards/pride/nonbinary.png", "Nonbinary", "<3", "pride", "pride"}
CARDS[304] = {"cards/pride/agender.png", "Agender", "<3", "pride", "pride"}
CARDS[305] = {"cards/pride/zedo.png", "Zedo", "", "pride", "pride"}
CARDS[306] = {"cards/flags/albania.png", "Albania", "", "pride", "pride"}
CARDS[307] = {"cards/flags/argentina.png", "Argentina", "", "pride", "pride"}
CARDS[308] = {"cards/flags/armenia.png", "Armenia", "", "pride", "pride"}
CARDS[309] = {"cards/flags/australia.png", "Australia", "", "pride", "pride"}
CARDS[310] = {"cards/flags/austria.png", "Austria", "", "pride", "pride"}
CARDS[311] = {"cards/flags/belgium.png", "Belgium", "", "pride", "pride"}
CARDS[312] = {"cards/flags/brazil.png", "Brazil", "", "pride", "pride"}
CARDS[313] = {"cards/flags/canada.png", "Canada", "", "pride", "pride"}
CARDS[314] = {"cards/flags/chile.png", "Chile", "", "pride", "pride"}
CARDS[315] = {"cards/flags/china.png", "China", "", "pride", "pride"}
CARDS[316] = {"cards/flags/colombia.png", "Colombia", "", "pride", "pride"}
CARDS[317] = {"cards/flags/czechia.png", "Czechia", "", "pride", "pride"}
CARDS[318] = {"cards/flags/denmark.png", "Denmark", "", "pride", "pride"}
CARDS[319] = {"cards/flags/ecuador.png", "Ecuador", "", "pride", "pride"}
CARDS[320] = {"cards/flags/england.png", "England", "", "pride", "pride"}
CARDS[321] = {"cards/flags/finland.png", "Finland", "", "pride", "pride"}
CARDS[322] = {"cards/flags/france.png", "France", "", "pride", "pride"}
CARDS[323] = {"cards/flags/germany.png", "Germany", "", "pride", "pride"}
CARDS[324] = {"cards/flags/greece.png", "Greece", "", "pride", "pride"}
CARDS[325] = {"cards/flags/hungary.png", "Hungary", "", "pride", "pride"}
CARDS[326] = {"cards/flags/india.png", "India", "", "pride", "pride"}
CARDS[327] = {"cards/flags/ireland.png", "Ireland", "", "pride", "pride"}
CARDS[328] = {"cards/flags/israel.png", "Israel", "", "pride", "pride"}
CARDS[329] = {"cards/flags/italy.png", "Italy", "", "pride", "pride"}
CARDS[330] = {"cards/flags/japan.png", "Japan", "", "pride", "pride"}
CARDS[331] = {"cards/flags/kuwait.png", "Kuwait", "", "pride", "pride"}
CARDS[332] = {"cards/flags/latvia.png", "Latvia", "", "pride", "pride"}
CARDS[333] = {"cards/flags/netherlands.png", "Netherlands", "", "pride", "pride"}
CARDS[334] = {"cards/flags/newzealand.png", "New Zealand", "", "pride", "pride"}
CARDS[335] = {"cards/flags/norway.png", "Norway", "", "pride", "pride"}
CARDS[336] = {"cards/flags/pakistan.png", "Pakistan", "", "pride", "pride"}
CARDS[337] = {"cards/flags/peru.png", "Peru", "", "pride", "pride"}
CARDS[338] = {"cards/flags/philippines.png", "Philippines", "", "pride", "pride"}
CARDS[339] = {"cards/flags/poland.png", "Poland", "", "pride", "pride"}
CARDS[340] = {"cards/flags/portugal.png", "Portugal", "", "pride", "pride"}
CARDS[341] = {"cards/flags/romania.png", "Romania", "", "pride", "pride"}
CARDS[342] = {"cards/flags/russia.png", "Russia", "", "pride", "pride"}
CARDS[343] = {"cards/flags/scotland.png", "Scotland", "", "pride", "pride"}
CARDS[344] = {"cards/flags/slovakia.png", "Slovakia", "", "pride", "pride"}
CARDS[345] = {"cards/flags/southkorea.png", "South Korea", "", "pride", "pride"}
CARDS[346] = {"cards/flags/spain.png", "Spain", "", "pride", "pride"}
CARDS[347] = {"cards/flags/sweden.png", "Sweden", "", "pride", "pride"}
CARDS[348] = {"cards/flags/thailand.png", "Thailand", "", "pride", "pride"}
CARDS[349] = {"cards/flags/turkey.png", "Turkey", "", "pride", "pride"}
CARDS[350] = {"cards/flags/uganda.png", "Uganda", "", "pride", "pride"}
CARDS[351] = {"cards/flags/ukraine.png", "Ukraine", "", "pride", "pride"}
CARDS[352] = {"cards/flags/unitedkingdom.png", "UK", "", "pride", "pride"}
CARDS[353] = {"cards/flags/unitedstates.png", "USA", "", "pride", "pride"}
CARDS[354] = {"cards/flags/venezuela.png", "Venezuela", "", "pride", "pride"}
CARDS[355] = {"cards/flags/vietnam.png", "Vietnam", "", "pride", "pride"}
CARDS[356] = {"cards/flags/wales.png", "Wales", "", "pride", "pride"}

QUOTES = {'"thank you for playing my gamemode <3" -Penial', '"a jeep wrangler is less aerodynamic than a lobster" -P0w', '"meow" -Megu', '"my grandma drowned, drowned in drip" -RandomSZ', '"skill issue" -Strike Force Lightning', '"told my wife im going to the bank, didnt tell her which one" -stiel', '"go lick a gas pump" -Bomca', '"justice for cradle, we the people demand" -RandomSZ', '"women fear me, fish want me" -Tomato', '"gang where are you, blud where are you" -White Guy', '"any kief slayers" -Cream', '"if i was a tree, i would have no reason to love a human" -suomij', '"i wish someone wanted me like plankton wanted the formula" -Seven', '"but your honor, babies kick pregnant women all the time" -MegaSlayer', '"by the nine im tweakin" -MegaSlayer', '"ball torture is $4 usd on steam" -Portanator', '"your walls are never safe from the drywall muncher" -Vertex', '"im obviously not racist, ive kissed a black man" -Mattimeo', '"my balls are made of one thing..." -RubberBalls', '"im like that" -Homeless', '"i need about tree fiddy" -Random Films', '"bring out the whole ocean" -Robo', '"can we ban this guy" -Poopy', '"root beer" -Plat', '"never forget 9/11" -afiais', '"praise o monolith" -Medinator', '"shut it mate yer da sells avon" -zee!', '"holy fishpaste" -Zenthic', '"titanmod servers are as stable as a girl with blue hair" -TheBean', '"titanmod is my favorite tactical shooter" -Computery', '"all bark no bite" -Tana', '"a gay man is shooting me" -emaad', '"getting a rainbow wont bring your father back" -SenorDragon', '"wobbler, its on sight" -blackchromatic', '"Hi" -sean', '"aim trainers dont work" -rA warden'}
